### ISSUE TITLE
yarn start执行出错

### ISSUE THREAD

**Issue by liulanglang22** [ManiaciaChao/yatm#7]
![image](https://user-images.githubusercontent.com/49188938/118117163-d2e1d980-b41d-11eb-9772-fa750eed2613.png)
执行yarn start之后报错如图：
yarn run v1.22.10
$ node ./dist/index.js
/home/all/tools/yatm/dist/index.js:15
    else if (consts_1.config.clipboard?.paste) {
                                                       ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
error Command failed with exit code 1.
我尝试把这个问号删除之后并没有解决问题，而是在下一个有？的地方继续报错，运行在Ubuntu20.04

**Comment by ManiaciaChao** [comment]
`?.`是较新的ECMAScript规范，请更新你的`node.js`版本。
